"""empty message

Revision ID: 2b923eefa73d
Revises: f69dd173be8d
Create Date: 2022-05-03 22:18:57.832253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b923eefa73d'
down_revision = 'f69dd173be8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorite_drink_name_key', 'favorite', type_='unique')
    op.drop_column('favorite', 'drink_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('drink_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.create_unique_constraint('favorite_drink_name_key', 'favorite', ['drink_name'])
    # ### end Alembic commands ###
