"""empty message

Revision ID: f5a15c32cf0d
Revises: 2b923eefa73d
Create Date: 2022-05-03 22:55:08.484900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a15c32cf0d'
down_revision = '2b923eefa73d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('drink_name', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'favorite', ['drink_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite', type_='unique')
    op.drop_column('favorite', 'drink_name')
    # ### end Alembic commands ###
